### ISSUE TITLE
Add support for double column type

### ISSUE THREAD

**Issue by erikzenker** [ontop/vig#3]

**Comment by tirrolo** [comment]
VIG currently supports a small superset of datatypes used in the database schema for the NPD benchmark (see https://github.com/ontop/npd-benchmark/wiki/datatypes for the list of supported datatypes). I assume you are trying to use the generator out of the benchmark. I will create a branch for you with experimental support for the datatypes mentioned in #2 and #3 .

Regards.

**Comment by tirrolo** [comment]
Solved in branch feature/doubleTimestampSupport
